project:
  type: website
  render: 
    - "*.qmd"
    - "!not_yet/"
  
website:
  title: "Datenanalyse in der Biologie"
  navbar:
    background: "#e7e0df"
    search: true
    logo: "https://www.bioquant.uni-heidelberg.de/themes/custom/bootstrap_bq/logo.svg"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged




